[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for linux/unix"
authors = ["poly000"]
license-file = "LICENSE"

[profile.release]
lto = true
strip = true
panic = "abort"

[dependencies]
# serializing
toml = "0.7.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.105"
rust_decimal = { version = "1.31.0", default-features = false, features = [
    "std",
] }
rust_decimal_macros = "1.31.0"

# lyric parse
lrc-nom = "0.2.0"

# ui
gtk = { version = "0.6.6", package = "gtk4" }

# MPRIS integration
dbus = "0.9.7"
mpris = "2.0.1"

# lyrics
smol = "1.3.0"
ncmapi = "0.1.13"
async-compat = "0.2.1"
reqwest = { version = "0.11.20", features = ["blocking"] }

# logging
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

# cache
md5 = "0.7.0"

# utils
regex = "1.9.3"
libc = "0.2.147"
xdg = "2.5.2"

# error handling
anyhow = "1.0.75"
thiserror = "1.0.47"
qqmusic-rs = { git = "https://github.com/waylyrics/qqmusic-rs.git", version = "0.1.0" }
url = "2.4.0"

[features]
vendored = ["dbus/vendored"]
default = []
