[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for linux/unix"
authors = ["poly000"]
license-file = "LICENSE"

[profile.release]
lto = true
strip = true
panic = "abort"

[dependencies]
# serializing
toml = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"
rust_decimal = { version = "1.32.0", default-features = false, features = [
    "std",
] }
rust_decimal_macros = "1.32.0"

# ui
gtk = { version = "0.7.3", package = "gtk4" }

# MPRIS integration
dbus = "0.9.7"
mpris = "2.0.1"
ncmapi = { git = "https://github.com/waylyrics/ncmapi-rs.git", version = "0.1.13" }
qqmusic-rs = { git = "https://github.com/waylyrics/qqmusic-rs.git", version = "0.1.0" }
lrc-nom = "0.2.0"
url = "2.4.1"

# logging
tracing = "0.1.37"
tracing-journald = "0.3.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

# cache
md5 = "0.7.0"

# utils
regex = "1.9.6"
libc = "0.2.148"
xdg = "2.5.2"

# error handling
anyhow = "1.0.75"
thiserror = "1.0.48"
glib-macros = "0.18.2"

async-trait = "0.1.73"
tokio = { version = "1.32.0", features = [
    "macros",
    "net",
    "time",
    "rt",
    "rt-multi-thread",
] }
reqwest = { version = "0.11.20" }
gidle_future = "0.2.0"

[features]
vendored = ["dbus/vendored"]
default = []
