[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for linux/unix"
authors = ["poly000"]
license-file = "LICENSE"

[profile.release]
lto = true
strip = true
panic = "abort"

[dependencies]
mimalloc = { version = "0.1.39", optional = true, default-features = false }

# serializing
toml = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
rust_decimal = { version = "1.33.1", default-features = false, features = [
    "std",
] }
rust_decimal_macros = "1.33.1"

# ui
gtk = { version = "0.7.3", package = "gtk4" }

# MPRIS integration
dbus = "0.9.7"
mpris = "2.0.1"
ncmapi = { git = "https://github.com/waylyrics/ncmapi-rs.git", rev = "394e9c2" }
qqmusic-rs = { git = "https://github.com/waylyrics/qqmusic-rs.git", rev = "402558f" }
lrc-nom = "0.2.0"
url = "2.5.0"

# logging
tracing = "0.1.40"
tracing-journald = "0.3.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# cache
md5 = "0.7.0"

# utils
regex = "1.10.2"
libc = "0.2.150"
xdg = "2.5.2"

# error handling
anyhow = "1.0.75"
thiserror = "1.0.50"
glib-macros = "0.18.3"

async-trait = "0.1.74"
tokio = { version = "1.34.0", features = [
    "macros",
    "net",
    "time",
    "rt",
    "rt-multi-thread",
] }
reqwest = { version = "0.11.20" }
once_cell = "1.19.0"

[features]
mimalloc = ["dep:mimalloc"]
vendored = ["dbus/vendored"]
default = ["mimalloc"]
