[package]
name = "waylyrics"
version = "0.1.0"
edition = "2021"
description = "Simple On Screen lyrics Display for wayland"
authors = ["poly000"]
license-file = "LICENSE"

default-run = "waylyrics"

[profile.release]
lto = "thin"
strip = true
panic = "abort"
opt-level = 3

[dependencies]
# configuration
toml = "0.7.6"
serde = { version = "1.0", features = ["derive"] }

# lyric parse
lrc-nom = "0.2.0"

# ui
gtk = { version = "0.6.6", package = "gtk4" }
ncmapi = "0.1.13"
dbus = "0.9.7"
mpris = "2.0.1"
rust_decimal = { version = "1.31.0", default-features = false, features = [
    "std",
] }
rust_decimal_macros = "1.30.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
md5 = "0.7.0"
serde_json = "1.0.104"
xdg = "2.5.2"
regex = "1.9.3"
smol = "1.3.0"
async-compat = "0.2.1"
anyhow = "1.0.72"
thiserror = "1.0.44"
libc = "0.2.147"

[features]
vendored = ["dbus/vendored"]
default = []
